---
# Source: pinger/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
  labels:
    app: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - args:
          - dual
        command:
        - /bin/server
        name: pinger
        image: gcr.io/testermctesterson/pinger:c41c691
        ports:
        - containerPort: 8080 
