---
# Source: pinger/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-prod
  labels:
    app: pinger-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger-prod
  template:
    metadata:
      labels:
        app: pinger-prod
    spec:
      containers:
      - args:
          - dual
        command:
        - /bin/server
        name: pinger-prod
        image: gcr.io/testermctesterson/
        ports:
        - containerPort: 8080 
