apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-prod
  labels:
    app: pinger-prod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pinger-prod
  template:
    metadata:
      labels:
        app: pinger-prod
    spec:
      containers:
      - args:
          - dual
        command:
        - /bin/server
        name: pinger-prod
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080 
